import "./global.css";

export const metadata = {
  title: "Zin Tools",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="">{children}</body>
    </html>
  );
}
